name: help_desk
description: "Una aplicación móvil para el sistema HelpDesk"
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.5.4

dependencies:
  animated_segmented_tab_control: ^2.0.0
  cupertino_icons: ^1.0.6
  diacritic: ^0.1.6
  dropdown_button2: ^2.3.9
  easy_stepper: ^0.8.5+1
  fancy_password_field: ^2.0.7
  file_picker: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localization: ^0.3.1
  flutter_secure_storage: ^9.2.2
  go_router: ^14.4.1
  google_nav_bar: ^5.0.7
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  meta: ^1.15.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  searchable_listview: ^2.15.2
  signature: ^6.0.0
  stop_watch_timer: ^3.2.1
  syncfusion_flutter_pdfviewer: ^28.2.5
  timelines_plus: ^1.0.4
  url_launcher: ^6.3.1

dev_dependencies:
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/app_icon.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/logos/
    - assets/images/icons/

  fonts:
    - family: NeueHaasUnica
      fonts:
        - asset: assets/fonts/NeueHaasUnica/NeueHaasUnica-regular.ttf
          style: normal
        - asset: assets/fonts/NeueHaasUnica/NeueHaasUnica-italic.ttf
          style: italic
        - asset: assets/fonts/NeueHaasUnica/NeueHaasUnica-Bold.ttf
        - asset: assets/fonts/NeueHaasUnica/NeueHaasUnica-BoldItalic.ttf
        - asset: assets/fonts/NeueHaasUnica/NeueHaasUnica-Light.ttf
